package org.ncbo.resource_access_tools.common.utils;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.HashMap;

import org.apache.log4j.Logger;

/**
 * used to manage output and error 
 * generated by processes launched using Runtime
 * 
 * @author  Adrien Coulet
 * @version OBR v1
 * @date    15-May-2009
 */
public class StreamGobbler extends Thread{
	// Logger for this class
	private static Logger logger = Logger.getLogger(StreamGobbler.class);
	
    InputStream is;
    String type;
    public static HashMap<Integer, String> lines;
    
    public StreamGobbler(InputStream is, String type){
        this.is = is;
        this.type = type;
        lines = new HashMap<Integer, String>();
    }
    
    public void run(){
        try{
            InputStreamReader isr = new InputStreamReader(is);

            BufferedReader br = new BufferedReader(isr);
            String line=null;
            int line_nb = 0;
            while ( (line = br.readLine()) != null){            	 
				if(type.equals("OUTPUT")){
				     lines.put(line_nb,line);
				}
				line_nb++;
            }            
        }catch (IOException ioe){
        	logger.error("", ioe);  
        }
    }
}
